// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: internal/proto/sentencepiece_model.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TrainerSpec_ModelType int32

const (
	TrainerSpec_UNIGRAM TrainerSpec_ModelType = 1
	TrainerSpec_BPE     TrainerSpec_ModelType = 2
	TrainerSpec_WORD    TrainerSpec_ModelType = 3
	TrainerSpec_CHAR    TrainerSpec_ModelType = 4
)

// Enum value maps for TrainerSpec_ModelType.
var (
	TrainerSpec_ModelType_name = map[int32]string{
		1: "UNIGRAM",
		2: "BPE",
		3: "WORD",
		4: "CHAR",
	}
	TrainerSpec_ModelType_value = map[string]int32{
		"UNIGRAM": 1,
		"BPE":     2,
		"WORD":    3,
		"CHAR":    4,
	}
)

func (x TrainerSpec_ModelType) Enum() *TrainerSpec_ModelType {
	p := new(TrainerSpec_ModelType)
	*p = x
	return p
}

func (x TrainerSpec_ModelType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TrainerSpec_ModelType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_proto_sentencepiece_model_proto_enumTypes[0].Descriptor()
}

func (TrainerSpec_ModelType) Type() protoreflect.EnumType {
	return &file_internal_proto_sentencepiece_model_proto_enumTypes[0]
}

func (x TrainerSpec_ModelType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *TrainerSpec_ModelType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = TrainerSpec_ModelType(num)
	return nil
}

// Deprecated: Use TrainerSpec_ModelType.Descriptor instead.
func (TrainerSpec_ModelType) EnumDescriptor() ([]byte, []int) {
	return file_internal_proto_sentencepiece_model_proto_rawDescGZIP(), []int{0, 0}
}

type ModelProto_SentencePiece_Type int32

const (
	ModelProto_SentencePiece_NORMAL       ModelProto_SentencePiece_Type = 1
	ModelProto_SentencePiece_UNKNOWN      ModelProto_SentencePiece_Type = 2
	ModelProto_SentencePiece_CONTROL      ModelProto_SentencePiece_Type = 3
	ModelProto_SentencePiece_USER_DEFINED ModelProto_SentencePiece_Type = 4
	ModelProto_SentencePiece_UNUSED       ModelProto_SentencePiece_Type = 5
	ModelProto_SentencePiece_BYTE         ModelProto_SentencePiece_Type = 6
)

// Enum value maps for ModelProto_SentencePiece_Type.
var (
	ModelProto_SentencePiece_Type_name = map[int32]string{
		1: "NORMAL",
		2: "UNKNOWN",
		3: "CONTROL",
		4: "USER_DEFINED",
		5: "UNUSED",
		6: "BYTE",
	}
	ModelProto_SentencePiece_Type_value = map[string]int32{
		"NORMAL":       1,
		"UNKNOWN":      2,
		"CONTROL":      3,
		"USER_DEFINED": 4,
		"UNUSED":       5,
		"BYTE":         6,
	}
)

func (x ModelProto_SentencePiece_Type) Enum() *ModelProto_SentencePiece_Type {
	p := new(ModelProto_SentencePiece_Type)
	*p = x
	return p
}

func (x ModelProto_SentencePiece_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ModelProto_SentencePiece_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_proto_sentencepiece_model_proto_enumTypes[1].Descriptor()
}

func (ModelProto_SentencePiece_Type) Type() protoreflect.EnumType {
	return &file_internal_proto_sentencepiece_model_proto_enumTypes[1]
}

func (x ModelProto_SentencePiece_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *ModelProto_SentencePiece_Type) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = ModelProto_SentencePiece_Type(num)
	return nil
}

// Deprecated: Use ModelProto_SentencePiece_Type.Descriptor instead.
func (ModelProto_SentencePiece_Type) EnumDescriptor() ([]byte, []int) {
	return file_internal_proto_sentencepiece_model_proto_rawDescGZIP(), []int{2, 0, 0}
}

type TrainerSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelType     *TrainerSpec_ModelType `protobuf:"varint,3,opt,name=model_type,json=modelType,enum=sentencepiece.TrainerSpec_ModelType,def=1" json:"model_type,omitempty"`
	UnkPiece      *string                `protobuf:"bytes,10,opt,name=unk_piece,json=unkPiece,def=<unk>" json:"unk_piece,omitempty"`
	BosPiece      *string                `protobuf:"bytes,11,opt,name=bos_piece,json=bosPiece,def=<s>" json:"bos_piece,omitempty"`
	EosPiece      *string                `protobuf:"bytes,12,opt,name=eos_piece,json=eosPiece,def=</s>" json:"eos_piece,omitempty"`
	PadPiece      *string                `protobuf:"bytes,13,opt,name=pad_piece,json=padPiece,def=<pad>" json:"pad_piece,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for TrainerSpec fields.
const (
	Default_TrainerSpec_ModelType = TrainerSpec_UNIGRAM
	Default_TrainerSpec_UnkPiece  = string("<unk>")
	Default_TrainerSpec_BosPiece  = string("<s>")
	Default_TrainerSpec_EosPiece  = string("</s>")
	Default_TrainerSpec_PadPiece  = string("<pad>")
)

func (x *TrainerSpec) Reset() {
	*x = TrainerSpec{}
	mi := &file_internal_proto_sentencepiece_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrainerSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainerSpec) ProtoMessage() {}

func (x *TrainerSpec) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_sentencepiece_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainerSpec.ProtoReflect.Descriptor instead.
func (*TrainerSpec) Descriptor() ([]byte, []int) {
	return file_internal_proto_sentencepiece_model_proto_rawDescGZIP(), []int{0}
}

func (x *TrainerSpec) GetModelType() TrainerSpec_ModelType {
	if x != nil && x.ModelType != nil {
		return *x.ModelType
	}
	return Default_TrainerSpec_ModelType
}

func (x *TrainerSpec) GetUnkPiece() string {
	if x != nil && x.UnkPiece != nil {
		return *x.UnkPiece
	}
	return Default_TrainerSpec_UnkPiece
}

func (x *TrainerSpec) GetBosPiece() string {
	if x != nil && x.BosPiece != nil {
		return *x.BosPiece
	}
	return Default_TrainerSpec_BosPiece
}

func (x *TrainerSpec) GetEosPiece() string {
	if x != nil && x.EosPiece != nil {
		return *x.EosPiece
	}
	return Default_TrainerSpec_EosPiece
}

func (x *TrainerSpec) GetPadPiece() string {
	if x != nil && x.PadPiece != nil {
		return *x.PadPiece
	}
	return Default_TrainerSpec_PadPiece
}

type NormalizerSpec struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Name                   *string                `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	PrecompiledCharsmap    *string                `protobuf:"bytes,2,opt,name=precompiled_charsmap,json=precompiledCharsmap" json:"precompiled_charsmap,omitempty"`
	AddDummyPrefix         *bool                  `protobuf:"varint,3,opt,name=add_dummy_prefix,json=addDummyPrefix,def=1" json:"add_dummy_prefix,omitempty"`
	RemoveExtraWhitespaces *bool                  `protobuf:"varint,4,opt,name=remove_extra_whitespaces,json=removeExtraWhitespaces,def=1" json:"remove_extra_whitespaces,omitempty"`
	EscapeWhitespaces      *bool                  `protobuf:"varint,5,opt,name=escape_whitespaces,json=escapeWhitespaces,def=1" json:"escape_whitespaces,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

// Default values for NormalizerSpec fields.
const (
	Default_NormalizerSpec_AddDummyPrefix         = bool(true)
	Default_NormalizerSpec_RemoveExtraWhitespaces = bool(true)
	Default_NormalizerSpec_EscapeWhitespaces      = bool(true)
)

func (x *NormalizerSpec) Reset() {
	*x = NormalizerSpec{}
	mi := &file_internal_proto_sentencepiece_model_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NormalizerSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NormalizerSpec) ProtoMessage() {}

func (x *NormalizerSpec) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_sentencepiece_model_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NormalizerSpec.ProtoReflect.Descriptor instead.
func (*NormalizerSpec) Descriptor() ([]byte, []int) {
	return file_internal_proto_sentencepiece_model_proto_rawDescGZIP(), []int{1}
}

func (x *NormalizerSpec) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *NormalizerSpec) GetPrecompiledCharsmap() string {
	if x != nil && x.PrecompiledCharsmap != nil {
		return *x.PrecompiledCharsmap
	}
	return ""
}

func (x *NormalizerSpec) GetAddDummyPrefix() bool {
	if x != nil && x.AddDummyPrefix != nil {
		return *x.AddDummyPrefix
	}
	return Default_NormalizerSpec_AddDummyPrefix
}

func (x *NormalizerSpec) GetRemoveExtraWhitespaces() bool {
	if x != nil && x.RemoveExtraWhitespaces != nil {
		return *x.RemoveExtraWhitespaces
	}
	return Default_NormalizerSpec_RemoveExtraWhitespaces
}

func (x *NormalizerSpec) GetEscapeWhitespaces() bool {
	if x != nil && x.EscapeWhitespaces != nil {
		return *x.EscapeWhitespaces
	}
	return Default_NormalizerSpec_EscapeWhitespaces
}

type ModelProto struct {
	state          protoimpl.MessageState      `protogen:"open.v1"`
	Pieces         []*ModelProto_SentencePiece `protobuf:"bytes,1,rep,name=pieces" json:"pieces,omitempty"`
	TrainerSpec    *TrainerSpec                `protobuf:"bytes,2,opt,name=trainer_spec,json=trainerSpec" json:"trainer_spec,omitempty"`
	NormalizerSpec *NormalizerSpec             `protobuf:"bytes,3,opt,name=normalizer_spec,json=normalizerSpec" json:"normalizer_spec,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ModelProto) Reset() {
	*x = ModelProto{}
	mi := &file_internal_proto_sentencepiece_model_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelProto) ProtoMessage() {}

func (x *ModelProto) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_sentencepiece_model_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelProto.ProtoReflect.Descriptor instead.
func (*ModelProto) Descriptor() ([]byte, []int) {
	return file_internal_proto_sentencepiece_model_proto_rawDescGZIP(), []int{2}
}

func (x *ModelProto) GetPieces() []*ModelProto_SentencePiece {
	if x != nil {
		return x.Pieces
	}
	return nil
}

func (x *ModelProto) GetTrainerSpec() *TrainerSpec {
	if x != nil {
		return x.TrainerSpec
	}
	return nil
}

func (x *ModelProto) GetNormalizerSpec() *NormalizerSpec {
	if x != nil {
		return x.NormalizerSpec
	}
	return nil
}

type ModelProto_SentencePiece struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Piece         *string                        `protobuf:"bytes,1,opt,name=piece" json:"piece,omitempty"`
	Score         *float32                       `protobuf:"fixed32,2,opt,name=score" json:"score,omitempty"`
	Type          *ModelProto_SentencePiece_Type `protobuf:"varint,3,opt,name=type,enum=sentencepiece.ModelProto_SentencePiece_Type,def=1" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for ModelProto_SentencePiece fields.
const (
	Default_ModelProto_SentencePiece_Type = ModelProto_SentencePiece_NORMAL
)

func (x *ModelProto_SentencePiece) Reset() {
	*x = ModelProto_SentencePiece{}
	mi := &file_internal_proto_sentencepiece_model_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelProto_SentencePiece) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelProto_SentencePiece) ProtoMessage() {}

func (x *ModelProto_SentencePiece) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_sentencepiece_model_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelProto_SentencePiece.ProtoReflect.Descriptor instead.
func (*ModelProto_SentencePiece) Descriptor() ([]byte, []int) {
	return file_internal_proto_sentencepiece_model_proto_rawDescGZIP(), []int{2, 0}
}

func (x *ModelProto_SentencePiece) GetPiece() string {
	if x != nil && x.Piece != nil {
		return *x.Piece
	}
	return ""
}

func (x *ModelProto_SentencePiece) GetScore() float32 {
	if x != nil && x.Score != nil {
		return *x.Score
	}
	return 0
}

func (x *ModelProto_SentencePiece) GetType() ModelProto_SentencePiece_Type {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return Default_ModelProto_SentencePiece_Type
}

var File_internal_proto_sentencepiece_model_proto protoreflect.FileDescriptor

const file_internal_proto_sentencepiece_model_proto_rawDesc = "" +
	"\n" +
	"(internal/proto/sentencepiece_model.proto\x12\rsentencepiece\"\x9f\x02\n" +
	"\vTrainerSpec\x12L\n" +
	"\n" +
	"model_type\x18\x03 \x01(\x0e2$.sentencepiece.TrainerSpec.ModelType:\aUNIGRAMR\tmodelType\x12\"\n" +
	"\tunk_piece\x18\n" +
	" \x01(\t:\x05<unk>R\bunkPiece\x12 \n" +
	"\tbos_piece\x18\v \x01(\t:\x03<s>R\bbosPiece\x12!\n" +
	"\teos_piece\x18\f \x01(\t:\x04</s>R\beosPiece\x12\"\n" +
	"\tpad_piece\x18\r \x01(\t:\x05<pad>R\bpadPiece\"5\n" +
	"\tModelType\x12\v\n" +
	"\aUNIGRAM\x10\x01\x12\a\n" +
	"\x03BPE\x10\x02\x12\b\n" +
	"\x04WORD\x10\x03\x12\b\n" +
	"\x04CHAR\x10\x04\"\xfc\x01\n" +
	"\x0eNormalizerSpec\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x121\n" +
	"\x14precompiled_charsmap\x18\x02 \x01(\tR\x13precompiledCharsmap\x12.\n" +
	"\x10add_dummy_prefix\x18\x03 \x01(\b:\x04trueR\x0eaddDummyPrefix\x12>\n" +
	"\x18remove_extra_whitespaces\x18\x04 \x01(\b:\x04trueR\x16removeExtraWhitespaces\x123\n" +
	"\x12escape_whitespaces\x18\x05 \x01(\b:\x04trueR\x11escapeWhitespaces\"\xb2\x03\n" +
	"\n" +
	"ModelProto\x12?\n" +
	"\x06pieces\x18\x01 \x03(\v2'.sentencepiece.ModelProto.SentencePieceR\x06pieces\x12=\n" +
	"\ftrainer_spec\x18\x02 \x01(\v2\x1a.sentencepiece.TrainerSpecR\vtrainerSpec\x12F\n" +
	"\x0fnormalizer_spec\x18\x03 \x01(\v2\x1d.sentencepiece.NormalizerSpecR\x0enormalizerSpec\x1a\xdb\x01\n" +
	"\rSentencePiece\x12\x14\n" +
	"\x05piece\x18\x01 \x01(\tR\x05piece\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x02R\x05score\x12H\n" +
	"\x04type\x18\x03 \x01(\x0e2,.sentencepiece.ModelProto.SentencePiece.Type:\x06NORMALR\x04type\"T\n" +
	"\x04Type\x12\n" +
	"\n" +
	"\x06NORMAL\x10\x01\x12\v\n" +
	"\aUNKNOWN\x10\x02\x12\v\n" +
	"\aCONTROL\x10\x03\x12\x10\n" +
	"\fUSER_DEFINED\x10\x04\x12\n" +
	"\n" +
	"\x06UNUSED\x10\x05\x12\b\n" +
	"\x04BYTE\x10\x06B/Z-github.com/jamesainslie/go-sat/internal/proto"

var (
	file_internal_proto_sentencepiece_model_proto_rawDescOnce sync.Once
	file_internal_proto_sentencepiece_model_proto_rawDescData []byte
)

func file_internal_proto_sentencepiece_model_proto_rawDescGZIP() []byte {
	file_internal_proto_sentencepiece_model_proto_rawDescOnce.Do(func() {
		file_internal_proto_sentencepiece_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_sentencepiece_model_proto_rawDesc), len(file_internal_proto_sentencepiece_model_proto_rawDesc)))
	})
	return file_internal_proto_sentencepiece_model_proto_rawDescData
}

var file_internal_proto_sentencepiece_model_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_internal_proto_sentencepiece_model_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_internal_proto_sentencepiece_model_proto_goTypes = []any{
	(TrainerSpec_ModelType)(0),         // 0: sentencepiece.TrainerSpec.ModelType
	(ModelProto_SentencePiece_Type)(0), // 1: sentencepiece.ModelProto.SentencePiece.Type
	(*TrainerSpec)(nil),                // 2: sentencepiece.TrainerSpec
	(*NormalizerSpec)(nil),             // 3: sentencepiece.NormalizerSpec
	(*ModelProto)(nil),                 // 4: sentencepiece.ModelProto
	(*ModelProto_SentencePiece)(nil),   // 5: sentencepiece.ModelProto.SentencePiece
}
var file_internal_proto_sentencepiece_model_proto_depIdxs = []int32{
	0, // 0: sentencepiece.TrainerSpec.model_type:type_name -> sentencepiece.TrainerSpec.ModelType
	5, // 1: sentencepiece.ModelProto.pieces:type_name -> sentencepiece.ModelProto.SentencePiece
	2, // 2: sentencepiece.ModelProto.trainer_spec:type_name -> sentencepiece.TrainerSpec
	3, // 3: sentencepiece.ModelProto.normalizer_spec:type_name -> sentencepiece.NormalizerSpec
	1, // 4: sentencepiece.ModelProto.SentencePiece.type:type_name -> sentencepiece.ModelProto.SentencePiece.Type
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_internal_proto_sentencepiece_model_proto_init() }
func file_internal_proto_sentencepiece_model_proto_init() {
	if File_internal_proto_sentencepiece_model_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_sentencepiece_model_proto_rawDesc), len(file_internal_proto_sentencepiece_model_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_proto_sentencepiece_model_proto_goTypes,
		DependencyIndexes: file_internal_proto_sentencepiece_model_proto_depIdxs,
		EnumInfos:         file_internal_proto_sentencepiece_model_proto_enumTypes,
		MessageInfos:      file_internal_proto_sentencepiece_model_proto_msgTypes,
	}.Build()
	File_internal_proto_sentencepiece_model_proto = out.File
	file_internal_proto_sentencepiece_model_proto_goTypes = nil
	file_internal_proto_sentencepiece_model_proto_depIdxs = nil
}
